//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmePro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci3
    {
        public int Sıra { get; set; }
        public Nullable<int> Numarası { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
    }
}
